fix: test formatter

diff --git a/.husky/hooks/pre-commit b/.husky/hooks/pre-commit
--- a/.husky/hooks/pre-commit
+++ b/.husky/hooks/pre-commit
@@ -1,3 +1,13 @@
 #!/bin/sh
-golangci-lint run
+golangci-lint run --fix
+if [ $? -ne 0 ]; then
+  echo "Linting errors found. Commit aborted."
+  exit 1
+fi
+
+# Jalankan gofumpt
 gofumpt -w .
+if [ $? -ne 0 ]; then
+  echo "Formatting errors found. Commit aborted."
+  exit 1
+fi
