feat: adding formatter

diff --git a/.husky/hooks/pre-commit b/.husky/hooks/pre-commit
--- a/.husky/hooks/pre-commit
+++ b/.husky/hooks/pre-commit
@@ -11,3 +11,9 @@ if [ $? -ne 0 ]; then
   echo "Formatting errors found. Commit aborted."
   exit 1
 fi
+
+goimports -w .
+if [ $? -ne 0 ]; then
+  echo "Goimports formatting errors found. Commit aborted."
+  exit 1
+fi
